name: 'React Client Build and Lint'

on:
  push:
    branches: [main]
    paths:
      - 'client/**'

jobs:
  build-client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install client dependencies
        run: |
          cd client
          npm install

      - name: Lint client code
        run: |
          cd client
          npm run lint

      - name: Build React client
        run: |
          cd client
          npm run build
