name: 'React Client Build and Lint'

on:
  push:
    branches: [main]

jobs:
  build-client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
         

      - name: Install client dependencies
        run: |
          cd client
          npm install

      - name: Lint client code
        run: |
          cd client
          npm run lint

      - name: Build React client
        run: |
          cd client
          npm run build
